### ISSUE TITLE
NtQueryDirectoryFile

### ISSUE THREAD

**Issue by MaggieKong** [bytecode77/r77-rootkit#100]
you deal with RETURN_SINGLE_ENTRY in NtQueryDirectoryFileEx,but leave returnSingleEntry in NtQueryDirectoryFile,should it be  dealt with ?
BTW,run a process as click on the "Run As Admin" option will use ShellExecuteEx to elevate the process,but what API ShellExecuteEx finally calls?I try to hook CreateProcessInternal,CreateProcessAsUser,and CreateProcessWithToken,it won't trigger any of those calls?Not even NtCreateUserProcess gets triggered

**Comment by bytecode77** [comment]
According to Microsoft, [NtQueryDirectoryFileEx](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfileex) handles this flag, but [NtQueryDirectoryFile](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfile) doesn't. The latter doesn't have the `queryFlags` parameter anyway.

`ShellExecute` eventually calls `CreateProcess`. There are numerous functions that can be used to create a process, however all of them end with `NtResumeThread` - a function that I hook in order to handle child process injection. Luckily, most features require only one hook in `ntdll.dll`, however some features can't be handled by only hooking ntdll.

**Comment by MaggieKong** [comment]
I hood explorer.exe with CreateProcessA and CreateProcessW,double click to run applications,hookedCreateProcessA or CreateProcesW will get triggered;however,if run application by "Run As Admin",CreateProcess won't get triggered.
hooking NtResumeThread will always get triggered,but I don't use reflected injection(many anti-virus blocks this),I use DetourCreateProcessWithdll to load the module

**Comment by bytecode77** [comment]
That's because running a process as admin launches **Consent.exe**, which then launches that process. Therefore, it's required to inject all newly created child processes, which is usually the case when installing the rootkit.

Anyway, `NtResumeThread` is the hook that you need, don't try to find all variatons of `CreateProcess*` and see whether you missed some of them...

**Comment by bytecode77** [comment]
Earlier I claimed that `NtQueryDirectoryFile` doesn't have a `queryFlags` parameter with a `SL_RETURN_SINGLE_ENTRY` value. That's true, but it has a `returnSingleEntry` function parameter that I've completely overlooked.

In issue #104, @wineggdrop reported this bug, too. This time I dug deeper and tested r77 on Windows 7, where the issue is fully reproducible.

I've just released **version 1.5.3** where this bug is fixed.
