### ISSUE TITLE
question

### ISSUE THREAD

**Issue by charlesmigel** [bytecode77/r77-rootkit#101]
"What crypting methods do you recommend?"

let me know thanks

**Comment by bytecode77** [comment]
??

**Comment by charlesmigel** [comment]
to encrypt the rootkit for FUD?

**Comment by bytecode77** [comment]
I take that you look for a quick solution to FUD the rootkit? Use the shellcode installer, the documentation explains how to use it and why. You cannot achieve scantime evasion of the executable.

**Comment by charlesmigel** [comment]
Thanks for answer but what about runtime FUD do you have solution there. Like the stager.exe/powershell  

let me know

**Comment by bytecode77** [comment]
r77 is already 100% fileless and evades AMSI. However, eventually AV vendors catch up and find some way to detect it, since r77 is popular open source software. It wouldn't make a lot of sense to spend weeks on fixing AV issues only to have them detected again a week later. It's up to the individual and their skills.

**Comment by charlesmigel** [comment]
oh okey i understand and question i need to crypt this part of the rootkit Several AV and EDR evasion techniques are in use:

    AMSI bypass: The PowerShell inline script disables AMSI by patching amsi.dll!AmsiScanBuffer to always return AMSI_RESULT_CLEAN. Polymorphism is used to evade signature detection of the AMSI bypass.      can you give some guidiens?

**Comment by bytecode77** [comment]
That's one possibility. You'll need to analyze what gets detected and change accordingly.

I could do this and publish the results, too. But this would take me weeks, after which my evasion will break days later. Anyway, since it's all fileless and so on, it's entirely possible. Can't say this about rootkits that use AppInit_DLL's.
