### ISSUE TITLE
GetProcessFileName() issue

### ISSUE THREAD

**Issue by wineggdrop** [bytecode77/r77-rootkit#105]
GetModuleFileNameExW will return ERROR_PARTIAL_COPY error in some cases so all calls from GetProcessFileName() will fail.

https://github.com/user-attachments/assets/8984b228-6b1f-4a45-b74e-124ce48ee6af

just check the TCP port 3389,it hides from netstat.exe but not mport.exe(it's a commandline tools using GetExtendedTcpTable() and GetExtendedTcpTable() API to get Listening port information).
BTW,it fails to hide ports in 32 bit netstat.exe as well,it seems this only happens in 32 bit application.

GetProcessImageFileName will solve that issue

**Comment by bytecode77** [comment]
Now that is really interesting... Espeically since I know about this issue with netstat not hiding in some cases, which was sitting in my backlog for years.

I really appreciate you explaining the bug in depth, even with a video and you even seem to have a solution at hand! It's really great, compared to the many times where I get one-liner GitHub issues with almost no description of the error, yet still the user who postet them somehow expected a bugfix...

Anyway, I'll probably get around fixing this within the next few days. I'll let you know :)

**Comment by bytecode77** [comment]
Okay, I created a new branch called #105 for you. Since I don't have your tool, it's best if you could check out the branch, compile and then test the changes against `mport.exe`.

I didn't look into the reason why `GetProcessFileName` doesn't work, but if I'd take a guess, it might run into another hook which then filters out the file that we actually want to check... touché.

**Comment by wineggdrop** [comment]
it works perfectly now

**Comment by bytecode77** [comment]
Allright, version **1.5.4** is released. Thank you very much for your constructive bug reports! It really helps to improve the quality of this project.
