### ISSUE TITLE
Some Config Question

### ISSUE THREAD

**Issue by 518651** [bytecode77/r77-rootkit#21]
Hello, Mr. author. Do you only need to add installstager.exe, r77-86ro64.dll, install.cpp, install. H, r77api. H and other files to integrate your project scheme into my project? I can't compile successfully with / MTD release x86
![{F8~M3XG8 F5VZP5@GN`%~Y](https://user-images.githubusercontent.com/69994181/143591198-364eb9f7-19b6-46fe-a191-1e0369c75327.png)

**Comment by bytecode77** [comment]
I'm guessing you want to replicate the behavior of `Install.exe` directly in your source code instead of deploying `Install.exe`, which is a good way to pack r77 with your project.

In your resources, you only need `InstallStager.exe`. It already contains both DLL's. You also don't need any *.lib files.

Install.cpp is the source code of `Install.exe`. So, you need to rename `WinMain` to e.g. `InstallR77` and then call that function. The r77api include is required for functions such as `GetResource` and `CreateScheduledTask`.

What error do you have when building?

**Comment by 518651** [comment]
Thank you for your reply. I will reconfigure r77 according to your method later. If there are any questions, I will give feedback
