### ISSUE TITLE
Tuto POC

### ISSUE THREAD

**Issue by Alien3407** [bytecode77/r77-rootkit#22]
Hello, First i want to thank you for this great rootkit, can you please make a Demo or a Poc using cobaltstrike or meterpreter shellcode.

**Comment by bytecode77** [comment]
You're welcome :)

I'm not familiar with cobaltstrike. But in order to make r77 easy to deploy, it comes as one single executable `Install.exe`. You only need this one file - it already contains both DLL's, etc.

It can be executed using RunPE, so if your meterpreter supports execution of 32-bit EXE files using RunPE, you can transfer Install.exe like that. Although this is rather generic advice, because like I said, I'm not familiar with cobaltstrike.

**Comment by Alien3407** [comment]
thanks for the quick answer,keep up the the good job
