### ISSUE TITLE
Hide custom registry Key/Value and Task Scheduler Tasks

### ISSUE THREAD

**Issue by thisisthelongestusernameyouhaveeverseen** [bytecode77/r77-rootkit#24]
Hi
i made registry key/value and task in task scheduler without $77 in their names
i was not able to hide them by adding their path to "HKLM\SOFTWARE\$77config\paths"

as you know there is some keys in registry that can't name them ourselves
but we maybe want to hide them (without losing their functionality)

will this be possible in future updates?

**Comment by bytecode77** [comment]
Hiding registry keys or values has medium to critical performance impact depending on how long it takes to process one item.

Let's say your registry key has 10 values, then the `HookedNtEnumerateKey` hook is triggered 10 times. Each time the hook is triggered, we need to iterate through the parent registry key up until the currently enumerated value is reached. This is due to the way the NT api handles registry enumeration.

Now, there is only a string comparison for the prefix. If we added string comparison for a list of names in addition, then the cost for each iteration would bring down OS performance, because registry queries are executed thousands of times per second by many processes.

Since r77 is designed to be stealth to the user, I prioritize performance in this case. But if you like to contribute, you could take a run and try out adding a registry key/value list in the configuration system, and hiding those. The right place in the code should be fairly easy to find and modify.

By the way, scheduled tasks are hidden implicitly by hiding their files. So, finding the **full** path and hiding *that* should do the trick. But it has to be the full absolute path to the job file.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
> If we added string comparison for a list of names in addition, then the cost for each iteration would bring down OS performance, because registry queries are executed thousands of times per second by many processes.

as you know many people are using process hacker or process explorer instead of task manager
but i guess nobody uses something else instead of windows default registry editor (regedit / regedt32)
you can set that ability to only hide the value / key from registry editor!
then system performance will not be slowed anymore
