### ISSUE TITLE
TestConsole without .NET Framework 4

### ISSUE THREAD

**Issue by thisisthelongestusernameyouhaveeverseen** [bytecode77/r77-rootkit#31]
Can you compile TestConsole to be able to run without .NET Framework 4
In Windows 7 / Windows Server 2008 can't run it without installing .NET Framework 4

**Comment by bytecode77** [comment]
The rootkit itself is designed to run with **any** CLR - unlike the Test Console.

Since the Test Console is not part of the rootkit deployment and it would require to write code and all dependencies "the old way", it only works with .NET 4.7. I, too, use various VM's for my testing and therefore also have to install .NET 4.7 in those VM's. Kind of a bummer, but much less effort than writing a WPF application using .NET 3.5.
