### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by josefredohd** [bytecode77/r77-rootkit#42]
I run the Install.exe file on a Windows 10 laptop and it doesn't hide anything, I tried it on another PC and it works.
So I don't understand why it doesn't work on my laptop.

**Comment by bytecode77** [comment]
Most likely due to AV detection. If AV detects the installation and blocks it, nothing is hidden. You can check using the Test Console whether installation was successful. If you turn off AV, it will definitely work.

Although the fileless concept along with many evasion techniques made r77 undetectable on the day of release, it certainly cannot keep AV vendors from creating signatures for existing releases. So, you probably need to do some adjustments if you want it to be FUD.

**Comment by josefredohd** [comment]
I have found out why this is happening.
The reason is because the laptop must be connected with the power cable, I was trying to install the rootkit but there was no success, so by chance I connected the charger to the laptop and the rootkit was installed out of nowhere.
And now it works correctly.
I tried it with another laptop and the same thing happened. Is this a bug?

**Comment by bytecode77** [comment]
Now this is new... I need to test this on a notebook with the power cable unplugged. If there is such a bug, I will release a new version with a fix right away. I'll do some testing...

**Comment by bytecode77** [comment]
Confirmed.

The installation worked up until the scheduled tasks were created. However they do not start when unplugged. I will need to fix this in `CreateScheduledTask` within the next few days.

![image](https://github.com/bytecode77/r77-rootkit/assets/34607975/3e8769c4-efe1-4a54-aaf1-cf3ff33520f3)

**Comment by bytecode77** [comment]
Fortunately, the bugfix was pretty straight forward. The scheduled task needs to be created with [DisallowStartIfOnBatteries](https://learn.microsoft.com/en-us/windows/win32/taskschd/tasksettings-disallowstartifonbatteries) set to `FALSE`.

```
settings->lpVtbl->put_DisallowStartIfOnBatteries(settings, VARIANT_FALSE);
```

Maybe `TRUE` is the default value, since OS vendors try to be more eco friendly...


### Version 1.4.3 is available for download.
