### ISSUE TITLE
hide icons from task bar 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [bytecode77/r77-rootkit#51]
hi, the is any way to hide app icon from taskbar ? 
( when i inject explorer its just hide app from folder and still show running apps icon on taskbar)

**Comment by bytecode77** [comment]
In a real world scenario, it makes no sense to hide a process, when the process is creating dialogs on the desktop. You would never write a stealthy application and then display, e.g., a MessageBox.

Typically, you develop an application that does not show any windows or dialogs, and then hide its process.

**Comment by BLACKGAMER1221** [comment]
its really helpful when you have some private/critical app with ui and need to be running but you use it on public/school pc or want to share your pc with other (your friend or family) , 
or simply use some external cheat on some games that have active admin and want to check your pc using anydesk 
 or maybe using external cheats on game center 
or hide some apps on your Workplace pc from supervisor
i found an easy solution to completely disable/toggle taskbar but if we can hide special app icon it much better

**Comment by bytecode77** [comment]
Okay, I understand your scenario better. r77 takes care of the process, files, etc... But hiding UI elements is certainly a custom implementation. There is no generic way to do this. Primarily because the application is no longer guaranteed to work, if its windows are hidden.

I can't do the programming for you, but you could implement something AutoIt-like, by finding windows of the process and trying to hide them, or setting opacity to 0. Then you need to store a script or EXE that does the window hiding.

**Comment by BLACKGAMER1221** [comment]
ok no problem, thanks for your communication
