### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by Mustwey** [bytecode77/r77-rootkit#58]
where do you learn to build such stuff? its so hard finding courses or material about the inner workings of a computer, can u tell me how u started?

**Comment by bytecode77** [comment]
For the most part, developing hacking tools is plain software development. Except that a software developer doesn't know anything about PE format, never heard of process hollowing and does not need to write any shellcode, and so on...

So, let's say you want to program a downloader? - It's nothing more than a program that downloads a file and runs it. If you want this to be fileless, you will soon find out that process hollowing (RunPE) is the technique to be used to achieve this. Since you're already a programmer, you will know how to integrate RunPE into your application.

And anything beyond that is just incremental learning of new techniques and using them in your tools. I've been programming for about 20 years and hacking for roughly 15 years. Therefore, I've picked up on lots of different techniques, so I can easily figure out which ones to use.

By the way, in r77, there is not a single technique that I've invented. The art is just in chaining everything together in the right way. And espeically, providing an installation & persistance process, which most rootkit developers fail to do.

**Comment by Mustwey** [comment]
so simply searching up what i want is the way to go?

**Comment by Mustwey** [comment]
are there any websites you recommend in which you search up stuff like a downloader

**Comment by Mustwey** [comment]
and which combo do you recommend? c & c++ or c# or all of them?

**Comment by bytecode77** [comment]
You should definitely learn programming really well before considering writing hacking tools. Otherwise you're just lost and confused the whole time. There's no way around writing the main part of your program yourself, even when you can copy some techniques off the internet.

Which programming language you use is not that important. C# is really easy to learn. C++ and C are not that easy to start programming with. Whatever you learn, just decide on a project and stick to it. You'll have plenty of challenges along the way and stuff to get familiar with in order to finish your project.

**Comment by Mustwey** [comment]
> You should definitely learn programming really well before considering writing hacking tools. Otherwise you're just lost and confused the whole time. There's no way around writing the main part of your program yourself, even when you can copy some techniques off the internet.
> 
> Which programming language you use is not that important. C# is really easy to learn. C++ and C are not that easy to start programming with. Whatever you learn, just decide on a project and stick to it. You'll have plenty of challenges along the way and stuff to get familiar with in order to finish your project.

thanks for the help, il still do c++ and c considering im learning java in my class and i heard they are very similar.
