### ISSUE TITLE
CRITICAL PROCESS BSOD

### ISSUE THREAD

**Issue by enverpasha** [bytecode77/r77-rootkit#6]
When I install install service 64, this screen meets why?

![Adsız](https://user-images.githubusercontent.com/79008871/110067662-3cda6480-7d85-11eb-94a1-d7d8a50efd4b.png)

**Comment by bytecode77** [comment]
There is a similar issue reported a few days ago. Can you tell from the EventViever, which process was injected with the rootit that caused the crash? Winlogon may show up in EventViewer, because it initialized the shutdown. But what's the first process that crashed? Can you show the first eventviewer log?

**Comment by enverpasha** [comment]
EventViewer:Kernel Power Problem

DUMPSTACK RESULTS:


[DumpStack.log](https://github.com/bytecode77/r77-rootkit/files/6088671/DumpStack.log)

**Comment by bytecode77** [comment]
This issue is fixed in 1.0.1. It was also reported in issue #5. Please feel free to re-open the issue, if it hasn't resolved on your testing environment.
