### ISSUE TITLE
ControlPipe using Powershell

### ISSUE THREAD

**Issue by APT-ZERO** [bytecode77/r77-rootkit#70]
Hi, Is it possible to control r77 using Powershell?

**Comment by bytecode77** [comment]
Sure. Since PowerShell allows you to use C#, you have full .NET capabilities. The example I have prodived is in C++, so you have to write it in .NET within PowerShell instead.

**Comment by bytecode77** [comment]
I guess you want to avoid a .NET DLL being compiled and written to disk, because in your workflow, you access the control pipe in a fileless manner? ;) I needed to avoid cmdlets, too, in the AMSI bypass. It was a pain...

Anyway, I saw a PS example [here](https://stackoverflow.com/questions/19433169/powershell-named-pipe-security) that shows code for writing to a named pipe. So it should be entirely possible.
