### ISSUE TITLE
Install.shellcode

### ISSUE THREAD

**Issue by sa6ta6ni6c** [bytecode77/r77-rootkit#79]
Hello!

I do not understand what is the point of shellcode installation, if it still drops Stager.exe on disk? The point of shellcode is for fileless execution, right?

**Comment by bytecode77** [comment]
The entire rootkit is fileless, and `Stager.exe` is written to the registry, not the disk. It can't be scanned by AV there in the same way a file is scanned.

And when using `Install.exe`, you should really execute it using RunPE. To save you the effort, I have written a shellcode variant of the installer, which already does RunPE for you, as you can see in the code - and that's why it's only 1 KB bigger.

**Comment by sa6ta6ni6c** [comment]
If I want to map Install.exe to memory (load in mem), should I compile it with x64_x86 or x86 and set it to autostart so it works? Or it is run once?

**Comment by bytecode77** [comment]
The **Installation** is required only once and persists r77 on the system, until you perform an **Uninstall**. The [documentation](https://docs.bytecode77.com/r77-rootkit/Technical%20Documentation.pdf) explains in some more depth what the installer does.

So, yes, you can map the shellcode to memory and execute it; Or you could run the `Install.exe` from disk (which I don't recommend). Either way, r77 will be persisted from that point forward with no files on the disk whatsoever.
